### ISSUE TITLE
Custom slide duration

### ISSUE THREAD

**Issue by aronstrandberg** [datasektionen/Meta-TV#64] opened 2015-11-18 19:42 UTC
Would be nice to set different duration on slides. Perhaps only when filtering by tags (it's useful during events) but not so nice when someone sets 5 minutes custom time during the day)

**Comment by LudwikJaniuk** [comment] 2015-11-18 20:29
This seems like it could be done with some kind of priority levels? Everyone is subjective on how mych time their own slide deserves, but if you decide say 3 "priority levels" and explain those people should adapt.

I think.

**Comment by Yopi** [comment] 2015-11-23 15:53
Duplicate of #54

**Closed by Yopi** 2015-11-23 15:53 UTC
Labels: duplicate, feature
